ALTER TABLE study_cafe
ADD COLUMN address VARCHAR(255),
ADD COLUMN image_urls JSONB,
ADD COLUMN phone_number VARCHAR(20),
ADD COLUMN facilities JSONB,
ADD COLUMN opening_hours VARCHAR(100),
ADD COLUMN description VARCHAR(50);

ALTER TABLE users
ADD COLUMN password VARCHAR(50) NOT NULL,
ADD COLUMN email VARCHAR(50),
ADD COLUMN phone VARCHAR(50),
ADD COLUMN image_url VARCHAR(100);
