name: ECR CI-CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ECR 로그인
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          883502293642.dkr.ecr.ap-southeast-2.amazonaws.com

      - name: Docker 이미지 빌드
        run: docker build -t seatly .

      - name: 태그 지정
        run: |
          docker tag seatly:latest \
          883502293642.dkr.ecr.ap-southeast-2.amazonaws.com/seatly:latest

      - name: ECR 푸시
        run: |
          docker push \
          883502293642.dkr.ecr.ap-southeast-2.amazonaws.com/seatly:latest

      - name: EC2 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            aws ecr get-login-password --region ap-southeast-2 | \
            docker login --username AWS --password-stdin \
            883502293642.dkr.ecr.ap-southeast-2.amazonaws.com

            docker pull 883502293642.dkr.ecr.ap-southeast-2.amazonaws.com/seatly:latest
            docker stop seatly || true
            docker rm seatly || true
            docker run -d \
              --name seatly \
              -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              883502293642.dkr.ecr.ap-southeast-2.amazonaws.com/seatly:latest
